# docker-compose.prod.yaml - Poduction extend
#version: '3.8'

services:
  api:
    build:
      args:
        APP_DEBUG: "false"
        ARG_COPY_FROM: "./src"
        ARG_COPY_DEST: "./src"
    environment:
      APP_DEBUG: "false"
    command: ["--workers", "4"]
  web_vue3:
    volumes:
      - web_html:/app/dist
  nginx:
    ports:
      - "80:80"
      #- "443:443"
    environment:
      NGINX_PORT: 80
      #NGINX_PORT: 443
      NGINX_SERVER_NAME: "${APP_BASE_URL}"
    volumes:
      - web_html:/usr/share/nginx/html


volumes:
  web_html: