# docker-compose.prod.yaml - Poduction extend

services:
  api:
    build:
      args:
        ARG_COPY_FROM: "./src"
        ARG_COPY_DEST: "./src"
    command: ["--workers", "4"]
  web_vue3:
    volumes:
      - web_html:/app/dist
  nginx:
    volumes:
      - web_html:/usr/share/nginx/html


volumes:
  web_html: