# docker-compose.dev.yaml - Development extend

services:
  api:
    volumes:
      - ./api:/app
    ports:
      - "${API_UVICORN_PORT:-8000}:${API_UVICORN_PORT:-8000}"
    command: ["--reload"]
  web_vue3:
    volumes:
      - ./web/vue3/app/dist:/app/dist
  nginx:
    volumes:
      - ./web/vue3/app/dist:/usr/share/nginx/html

