from sqlalchemy.ext.asyncio import AsyncSession

from src.models.books import BookModel
from src.models.base import Base


# Debug Reset and Setup Database
async def setup_database(session: AsyncSession):
    async with session.bind.begin() as conn:
        await conn.run_sync(Base.metadata.drop_all)
        await conn.run_sync(Base.metadata.create_all)

    new_book = BookModel(
        title = 'Nineteen Eighty-Four',
        author = 'George Orwell',
    )
    session.add(new_book)
    new_book = BookModel(
        title = 'For Whom the Bell Tolls',
        author = 'Ernest Miller Hemingway',
    )
    session.add(new_book)
    await session.commit()

    new_book = BookModel(title='The Lord of the Rings', author='J. R. R. Tolkien')
    session.add(new_book)
    new_book = BookModel(title='Pride and Prejudice', author='Jane Austen')
    session.add(new_book)
    new_book = BookModel(title='His Dark Materials', author='Philip Pullman')
    session.add(new_book)
    new_book = BookModel(title='The Hitchhiker\'s Guide to the Galaxy', author='Douglas Adams')
    session.add(new_book)
    new_book = BookModel(title='Harry Potter and the Goblet of Fire', author='J. K. Rowling')
    session.add(new_book)
    new_book = BookModel(title='To Kill a Mockingbird', author='Harper Lee')
    session.add(new_book)
    new_book = BookModel(title='Winnie-the-Pooh', author='A. A. Milne')
    session.add(new_book)
    new_book = BookModel(title='Nineteen Eighty-Four', author='George Orwell')
    session.add(new_book)
    new_book = BookModel(title='The Lion, the Witch and the Wardrobe', author='C. S. Lewis')
    session.add(new_book)
    new_book = BookModel(title='Jane Eyre', author='Charlotte Brontë')
    session.add(new_book)
    new_book = BookModel(title='Catch-22', author='Joseph Heller')
    session.add(new_book)
    new_book = BookModel(title='Wuthering Heights', author='Emily Brontë')
    session.add(new_book)
    new_book = BookModel(title='Birdsong', author='Sebastian Faulks')
    session.add(new_book)
    new_book = BookModel(title='Rebecca', author='Daphne du Maurier')
    session.add(new_book)
    new_book = BookModel(title='The Catcher in the Rye', author='J. D. Salinger')
    session.add(new_book)
    new_book = BookModel(title='The Wind in the Willows', author='Kenneth Grahame')
    session.add(new_book)
    new_book = BookModel(title='Great Expectations', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='Little Women', author='Louisa May Alcott')
    session.add(new_book)
    new_book = BookModel(title='Captain Corelli\'s Mandolin', author='Louis de Bernières')
    session.add(new_book)
    new_book = BookModel(title='War and Peace', author='Leo Tolstoy')
    session.add(new_book)
    new_book = BookModel(title='Gone with the Wind', author='Margaret Mitchell')
    session.add(new_book)
    new_book = BookModel(title='Harry Potter and the Philosopher\'s Stone', author='J. K. Rowling')
    session.add(new_book)
    new_book = BookModel(title='Harry Potter and the Chamber of Secrets', author='J. K. Rowling')
    session.add(new_book)
    new_book = BookModel(title='Harry Potter and the Prisoner of Azkaban', author='J. K. Rowling')
    session.add(new_book)
    new_book = BookModel(title='The Hobbit', author='J. R. R. Tolkien')
    session.add(new_book)
    new_book = BookModel(title='Tess of the d\'Urbervilles', author='Thomas Hardy')
    session.add(new_book)
    new_book = BookModel(title='Middlemarch', author='George Eliot')
    session.add(new_book)
    new_book = BookModel(title='A Prayer for Owen Meany', author='John Irving')
    session.add(new_book)
    new_book = BookModel(title='The Grapes of Wrath', author='John Steinbeck')
    session.add(new_book)
    new_book = BookModel(title='Alice\'s Adventures in Wonderland', author='Lewis Carroll')
    session.add(new_book)
    new_book = BookModel(title='The Story of Tracy Beaker', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='One Hundred Years of Solitude', author='Gabriel García Márquez')
    session.add(new_book)
    new_book = BookModel(title='The Pillars of the Earth', author='Ken Follett')
    session.add(new_book)
    new_book = BookModel(title='David Copperfield', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='Charlie and the Chocolate Factory', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='Treasure Island', author='Robert Louis Stevenson')
    session.add(new_book)
    new_book = BookModel(title='A Town Like Alice', author='Nevil Shute')
    session.add(new_book)
    new_book = BookModel(title='Persuasion', author='Jane Austen')
    session.add(new_book)
    new_book = BookModel(title='Dune', author='Frank Herbert')
    session.add(new_book)
    new_book = BookModel(title='Emma', author='Jane Austen')
    session.add(new_book)
    new_book = BookModel(title='Anne of Green Gables', author='Lucy Maud Montgomery')
    session.add(new_book)
    new_book = BookModel(title='Watership Down', author='Richard Adams')
    session.add(new_book)
    new_book = BookModel(title='The Great Gatsby', author='F. Scott Fitzgerald')
    session.add(new_book)
    new_book = BookModel(title='The Count of Monte Cristo', author='Alexandre Dumas')
    session.add(new_book)
    new_book = BookModel(title='Brideshead Revisited', author='Evelyn Waugh')
    session.add(new_book)
    new_book = BookModel(title='Animal Farm', author='George Orwell')
    session.add(new_book)
    new_book = BookModel(title='A Christmas Carol', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='Far from the Madding Crowd', author='Thomas Hardy')
    session.add(new_book)
    new_book = BookModel(title='Goodnight Mister Tom', author='Michelle Magorian')
    session.add(new_book)
    new_book = BookModel(title='The Shell Seekers', author='Rosamunde Pilcher')
    session.add(new_book)
    new_book = BookModel(title='The Secret Garden', author='Frances Hodgson Burnett')
    session.add(new_book)
    new_book = BookModel(title='Of Mice and Men', author='John Steinbeck')
    session.add(new_book)
    new_book = BookModel(title='The Stand', author='Stephen King')
    session.add(new_book)
    new_book = BookModel(title='Anna Karenina', author='Leo Tolstoy')
    session.add(new_book)
    new_book = BookModel(title='A Suitable Boy', author='Vikram Seth')
    session.add(new_book)
    new_book = BookModel(title='The BFG', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='Swallows and Amazons', author='Arthur Ransome')
    session.add(new_book)
    new_book = BookModel(title='Black Beauty', author='Anna Sewell')
    session.add(new_book)
    new_book = BookModel(title='Artemis Fowl', author='Eoin Colfer')
    session.add(new_book)
    new_book = BookModel(title='Crime and Punishment', author='Fyodor Dostoyevsky')
    session.add(new_book)
    new_book = BookModel(title='Noughts & Crosses', author='Malorie Blackman')
    session.add(new_book)
    new_book = BookModel(title='Memoirs of a Geisha', author='Arthur Golden')
    session.add(new_book)
    new_book = BookModel(title='A Tale of Two Cities', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='The Thorn Birds', author='Colleen McCullough')
    session.add(new_book)
    new_book = BookModel(title='Mort', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Magic Faraway Tree', author='Enid Blyton')
    session.add(new_book)
    new_book = BookModel(title='The Magus', author='John Fowles')
    session.add(new_book)
    new_book = BookModel(title='Good Omens', author='Neil Gaiman and Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Guards! Guards!', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Lord of the Flies', author='William Golding')
    session.add(new_book)
    new_book = BookModel(title='Perfume', author='Patrick Süskind')
    session.add(new_book)
    new_book = BookModel(title='The Ragged-Trousered Philanthropists', author='Robert Tressell')
    session.add(new_book)
    new_book = BookModel(title='Night Watch', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Matilda', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='Bridget Jones\'s Diary', author='Helen Fielding')
    session.add(new_book)
    new_book = BookModel(title='The Secret History', author='Donna Tartt')
    session.add(new_book)
    new_book = BookModel(title='The Woman in White', author='Wilkie Collins')
    session.add(new_book)
    new_book = BookModel(title='Ulysses', author='James Joyce')
    session.add(new_book)
    new_book = BookModel(title='Bleak House', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='Double Act', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='The Twits', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='I Capture the Castle', author='Dodie Smith')
    session.add(new_book)
    new_book = BookModel(title='Holes', author='Louis Sachar')
    session.add(new_book)
    new_book = BookModel(title='Gormenghast', author='Mervyn Peake')
    session.add(new_book)
    new_book = BookModel(title='The God of Small Things', author='Arundhati Roy')
    session.add(new_book)
    new_book = BookModel(title='Vicky Angel', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Brave New World', author='Aldous Huxley')
    session.add(new_book)
    new_book = BookModel(title='Cold Comfort Farm', author='Stella Gibbons')
    session.add(new_book)
    new_book = BookModel(title='Magician', author='Raymond E. Feist')
    session.add(new_book)
    new_book = BookModel(title='On the Road', author='Jack Kerouac')
    session.add(new_book)
    new_book = BookModel(title='The Godfather', author='Mario Puzo')
    session.add(new_book)
    new_book = BookModel(title='The Clan of the Cave Bear', author='Jean M. Auel')
    session.add(new_book)
    new_book = BookModel(title='The Colour of Magic', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Alchemist', author='Paulo Coelho')
    session.add(new_book)
    new_book = BookModel(title='Katherine', author='Anya Seton')
    session.add(new_book)
    new_book = BookModel(title='Kane and Abel', author='Jeffrey Archer')
    session.add(new_book)
    new_book = BookModel(title='Love in the Time of Cholera', author='Gabriel García Márquez')
    session.add(new_book)
    new_book = BookModel(title='Girls in Love', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='The Princess Diaries', author='Meg Cabot')
    session.add(new_book)
    new_book = BookModel(title='Midnight\'s Children', author='Salman Rushdie')
    session.add(new_book)
    new_book = BookModel(title='Three Men in a Boat', author='Jerome K. Jerome')
    session.add(new_book)
    new_book = BookModel(title='Small Gods', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Beach', author='Alex Garland')
    session.add(new_book)
    new_book = BookModel(title='Dracula', author='Bram Stoker')
    session.add(new_book)
    new_book = BookModel(title='Point Blanc', author='Anthony Horowitz')
    session.add(new_book)
    new_book = BookModel(title='The Pickwick Papers', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='Stormbreaker', author='Anthony Horowitz')
    session.add(new_book)
    new_book = BookModel(title='The Wasp Factory', author='Iain Banks')
    session.add(new_book)
    new_book = BookModel(title='The Day of the Jackal', author='Frederick Forsyth')
    session.add(new_book)
    new_book = BookModel(title='The Illustrated Mum', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Jude the Obscure', author='Thomas Hardy')
    session.add(new_book)
    new_book = BookModel(title='The Secret Diary of Adrian Mole, Aged 13¾', author='Sue Townsend')
    session.add(new_book)
    new_book = BookModel(title='The Cruel Sea', author='Nicholas Monsarrat')
    session.add(new_book)
    new_book = BookModel(title='Les Misérables', author='Victor Hugo')
    session.add(new_book)
    new_book = BookModel(title='The Mayor of Casterbridge', author='Thomas Hardy')
    session.add(new_book)
    new_book = BookModel(title='The Dare Game', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Bad Girls', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='The Picture of Dorian Gray', author='Oscar Wilde')
    session.add(new_book)
    new_book = BookModel(title='Shōgun', author='James Clavell')
    session.add(new_book)
    new_book = BookModel(title='The Day of the Triffids', author='John Wyndham')
    session.add(new_book)
    new_book = BookModel(title='Lola Rose', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Vanity Fair', author='William Makepeace Thackeray')
    session.add(new_book)
    new_book = BookModel(title='The Forsyte Saga', author='John Galsworthy')
    session.add(new_book)
    new_book = BookModel(title='House of Leaves', author='Mark Z. Danielewski')
    session.add(new_book)
    new_book = BookModel(title='The Poisonwood Bible', author='Barbara Kingsolver')
    session.add(new_book)
    new_book = BookModel(title='Reaper Man', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Angus, Thongs and Full-Frontal Snogging', author='Louise Rennison')
    session.add(new_book)
    new_book = BookModel(title='The Hound of the Baskervilles', author='Arthur Conan Doyle')
    session.add(new_book)
    new_book = BookModel(title='Possession: A Romance', author='A. S. Byatt')
    session.add(new_book)
    new_book = BookModel(title='The Master and Margarita', author='Mikhail Bulgakov')
    session.add(new_book)
    new_book = BookModel(title='The Handmaid\'s Tale', author='Margaret Atwood')
    session.add(new_book)
    new_book = BookModel(title='Danny, the Champion of the World', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='East of Eden', author='John Steinbeck')
    session.add(new_book)
    new_book = BookModel(title='George\'s Marvellous Medicine', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='Wyrd Sisters', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Color Purple', author='Alice Walker')
    session.add(new_book)
    new_book = BookModel(title='Hogfather', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Thirty-Nine Steps', author='John Buchan')
    session.add(new_book)
    new_book = BookModel(title='Girls in Tears', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Sleepovers', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='All Quiet on the Western Front', author='Erich Maria Remarque')
    session.add(new_book)
    new_book = BookModel(title='Behind the Scenes at the Museum', author='Kate Atkinson')
    session.add(new_book)
    new_book = BookModel(title='High Fidelity', author='Nick Hornby')
    session.add(new_book)
    new_book = BookModel(title='It', author='Stephen King')
    session.add(new_book)
    new_book = BookModel(title='James and the Giant Peach', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='The Green Mile', author='Stephen King')
    session.add(new_book)
    new_book = BookModel(title='Papillon', author='Henri Charrière')
    session.add(new_book)
    new_book = BookModel(title='Men at Arms', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Master and Commander', author='Patrick O\'Brian')
    session.add(new_book)
    new_book = BookModel(title='Skeleton Key', author='Anthony Horowitz')
    session.add(new_book)
    new_book = BookModel(title='Soul Music', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Thief of Time', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Fifth Elephant', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='Atonement', author='Ian McEwan')
    session.add(new_book)
    new_book = BookModel(title='Secrets', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='The Silver Sword', author='Ian Serraillier')
    session.add(new_book)
    new_book = BookModel(title='One Flew Over the Cuckoo\'s Nest', author='Ken Kesey')
    session.add(new_book)
    new_book = BookModel(title='Heart of Darkness', author='Joseph Conrad')
    session.add(new_book)
    new_book = BookModel(title='Kim', author='Rudyard Kipling')
    session.add(new_book)
    new_book = BookModel(title='Cross Stitch', author='Diana Gabaldon')
    session.add(new_book)
    new_book = BookModel(title='Moby-Dick', author='Herman Melville')
    session.add(new_book)
    new_book = BookModel(title='River God', author='Wilbur Smith')
    session.add(new_book)
    new_book = BookModel(title='Sunset Song', author='Lewis Grassic Gibbon')
    session.add(new_book)
    new_book = BookModel(title='The Shipping News', author='E. Annie Proulx')
    session.add(new_book)
    new_book = BookModel(title='The World According to Garp', author='John Irving')
    session.add(new_book)
    new_book = BookModel(title='Lorna Doone', author='R. D. Blackmore')
    session.add(new_book)
    new_book = BookModel(title='Girls Out Late', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='The Far Pavilions', author='M. M. Kaye')
    session.add(new_book)
    new_book = BookModel(title='The Witches', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='Charlotte\'s Web', author='E. B. White')
    session.add(new_book)
    new_book = BookModel(title='Frankenstein', author='Mary Shelley')
    session.add(new_book)
    new_book = BookModel(title='They Used to Play on Grass', author='Terry Venables and Gordon Williams')
    session.add(new_book)
    new_book = BookModel(title='The Old Man and the Sea', author='Ernest Hemingway')
    session.add(new_book)
    new_book = BookModel(title='The Name of the Rose', author='Umberto Eco')
    session.add(new_book)
    new_book = BookModel(title='Sophie\'s World', author='Jostein Gaarder')
    session.add(new_book)
    new_book = BookModel(title='Dustbin Baby', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Fantastic Mr Fox', author='Roald Dahl')
    session.add(new_book)
    new_book = BookModel(title='Lolita', author='Vladimir Nabokov')
    session.add(new_book)
    new_book = BookModel(title='Jonathan Livingston Seagull', author='Richard Bach')
    session.add(new_book)
    new_book = BookModel(title='The Little Prince', author='Antoine de Saint-Exupéry')
    session.add(new_book)
    new_book = BookModel(title='The Suitcase Kid', author='Jacqueline Wilson')
    session.add(new_book)
    new_book = BookModel(title='Oliver Twist', author='Charles Dickens')
    session.add(new_book)
    new_book = BookModel(title='The Power of One', author='Bryce Courtenay')
    session.add(new_book)
    new_book = BookModel(title='Silas Marner', author='George Eliot')
    session.add(new_book)
    new_book = BookModel(title='American Psycho', author='Bret Easton Ellis')
    session.add(new_book)
    new_book = BookModel(title='The Diary of a Nobody', author='George and Weedon Grossmith')
    session.add(new_book)
    new_book = BookModel(title='Trainspotting', author='Irvine Welsh')
    session.add(new_book)
    new_book = BookModel(title='Goosebumps', author='R. L. Stine')
    session.add(new_book)
    new_book = BookModel(title='Heidi', author='Johanna Spyri')
    session.add(new_book)
    new_book = BookModel(title='Sons and Lovers', author='D. H. Lawrence')
    session.add(new_book)
    new_book = BookModel(title='The Unbearable Lightness of Being', author='Milan Kundera')
    session.add(new_book)
    new_book = BookModel(title='Man and Boy', author='Tony Parsons')
    session.add(new_book)
    new_book = BookModel(title='The Truth', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The War of the Worlds', author='H. G. Wells')
    session.add(new_book)
    new_book = BookModel(title='The Horse Whisperer', author='Nicholas Evans')
    session.add(new_book)
    new_book = BookModel(title='A Fine Balance', author='Rohinton Mistry')
    session.add(new_book)
    new_book = BookModel(title='Witches Abroad', author='Terry Pratchett')
    session.add(new_book)
    new_book = BookModel(title='The Once and Future King', author='T. H. White')
    session.add(new_book)
    new_book = BookModel(title='The Very Hungry Caterpillar', author='Eric Carle')
    session.add(new_book)
    new_book = BookModel(title='Flowers in the Attic', author='V. C. Andrews')
    session.add(new_book)
    await session.commit()
